### ISSUE TITLE
[API Enhancement] Remove PathPlanner dependency

### ISSUE THREAD

**Issue by oh-yes-0-fps** [Shenzhen-Robotics-Alliance/maple-sim#10]
It's never used in the project. That's about it.

**Comment by catr1xLiu** [comment]
pathplanner dependency is  removed when upgrading to wpilib 2025, thanks for the suggestion!
https://github.com/Shenzhen-Robotics-Alliance/maple-sim/commit/6e20f17eeb702216b14cc746382468fc1ce8f407#diff-2f1843f61396b1c72cb2d8e06f4950a944079bb1ce391b90289ec00b18108507
