### ISSUE TITLE
[BUG] Generated javadocs in git diff

### ISSUE THREAD

**Issue by oh-yes-0-fps** [Shenzhen-Robotics-Alliance/maple-sim#13]
Having the javadocs not gitignored makes commit diffs cluttered and can inflate the lines/files changed for a pr or commit. I haven't looked super close into your workflow setup yet but its atypical for these to be included like this.

**Comment by catr1xLiu** [comment]
Yes, you're right, I also think it's not a good idea to always manually commit the java docs.  But I'm bad at github worflows, so if you can help me on that it would be great.  Looking forward to your PR!

**Comment by catr1xLiu** [comment]
Javadocs are now generated to /javadocs/, which is gitignored.  When we do "gradlew publish" it will copy all the javadocs to docs/javadocs which will be deployed to github pages.

Thanks for the suggestion!

https://github.com/Shenzhen-Robotics-Alliance/maple-sim/commit/18bce087acb46f9066cc2e2ff04fd67c191b9f4a
