### ISSUE TITLE
[BUG]-"Quick Start 404"

### ISSUE THREAD

**Issue by ThatChair** [Shenzhen-Robotics-Alliance/maple-sim#31]
## Bug Description
All of the links in the 'Quick Start' section of README.md link to files that don't exist.

**Comment by catr1xLiu** [comment]
https://github.com/Shenzhen-Robotics-Alliance/maple-sim/commit/2ad726e42399d7d4973570818d75572c2220ce6d

This should work, thanks for reporting!
