### ISSUE TITLE
Robot Spinning

### ISSUE THREAD

**Issue by adurstewitz** [Shenzhen-Robotics-Alliance/maple-sim#41]
Loaded up the AdvantageKit_AdvancedSwerveDriveProject and the robot is just spinning on the Advantage Scope. Using an xbox wireless controller on a Macbook Pro. All x,y coordinates are stable in Network Tables. Any help is appreciated!

**Comment by catr1xLiu** [comment]
This seems like a joystick mapping issue, please check the "joystick" view in AdvantageScope.
