### ISSUE TITLE
[API Enhancement] Using wpilib units api for everything

### ISSUE THREAD

**Issue by oh-yes-0-fps** [Shenzhen-Robotics-Alliance/maple-sim#9]
The performance burden of this library is much looser due to the fact the code should only ever run on a PC. With this consideration I believe using the [wpilib java units library](https://docs.wpilib.org/en/latest/docs/software/basic-programming/java-units.html#the-java-units-library) for everything from the start would be a good idea. The reason everything in wpilib isn't in units is because of the overhead which doesn't matter here.

**Comment by catr1xLiu** [comment]
I agree.  It seems like wpilib2025 is very strict on using the units library, it keeps yelling at me about that when I compile.
If you have time to work on that and create a pull request, I'll be really grateful.

**Comment by catr1xLiu** [comment]
wpilib units library is implemented in all user APIs in #24
